server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #链接注册中心的地址
spring:
  application:
    name: provider #服务的名字
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 20000
    password: wang
  data:
      mongodb:
          uri: mongodb://localhost:27017/mr
      solr:
        host: http://localhost:8088/solr
  devtools:
    restart:
     enabled: true
  datasource:
        username: root
        password: 95190714
        url: jdbc:mysql://127.0.0.1:3306/retailers?serverTimezone=GMT
        type: com.alibaba.druid.pool.DruidDataSource
  logging:
    level:
      com:
      mr: debug
