server:
  port: 8766
spring:
  application:
    name: consumer-ribbon
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/